import MobileNavigation, { DesktopNavigation } from '@/components/Navigation';
import Copyright from '@/app/components/Copyright';
import { getAllEssays } from '@/lib/server/essays.server';

type Axis = {
  name: string;
  left: string;
  right: string;
  leftWords: string[];
  rightWords: string[];
};

function countMatches(text: string, words: string[]): number {
  return words.reduce((acc, word) => acc + (text.match(new RegExp(word, 'g')) || []).length, 0);
}

function topEssayTitles(
  entries: Array<{ title: string; text: string }>,
  words: string[],
  limit = 3
): string[] {
  return entries
    .map((entry) => ({ title: entry.title, score: countMatches(entry.text, words) }))
    .filter((entry) => entry.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((entry) => entry.title);
}

export default async function PlayerPage() {
  const essays = await getAllEssays();
  const entries = essays.map((essay) => ({
    title: essay.metadata.title,
    text: `${essay.metadata.title} ${essay.content}`.toLowerCase(),
  }));
  const corpus = entries.map((entry) => entry.text).join(' ');

  const mbtiAxes: Axis[] = [
    {
      name: 'I/E',
      left: 'I',
      right: 'E',
      leftWords: ['writing', 'thinking', 'reflect', 'alone', 'question'],
      rightWords: ['people', 'community', 'team', 'share', 'talk'],
    },
    {
      name: 'N/S',
      left: 'N',
      right: 'S',
      leftWords: ['system', 'model', 'framework', 'meaning', 'abstract', 'why'],
      rightWords: ['routine', 'process', 'steps', 'daily', 'practical'],
    },
    {
      name: 'T/F',
      left: 'T',
      right: 'F',
      leftWords: ['logic', 'first principles', 'structure', 'analysis', 'design'],
      rightWords: ['feel', 'emotion', 'love', 'connection', 'empathy'],
    },
    {
      name: 'J/P',
      left: 'J',
      right: 'P',
      leftWords: ['kpi', 'goal', 'plan', 'discipline', 'optimi'],
      rightWords: ['uncertainty', 'unknown', 'adapt', 'just start', 'serendipity'],
    },
  ];

  const mbtiLetters = mbtiAxes.map((axis) => {
    const left = countMatches(corpus, axis.leftWords);
    const right = countMatches(corpus, axis.rightWords);
    return left >= right ? axis.left : axis.right;
  });
  const mbtiGuess = mbtiLetters.join('');

  const systemsEvidence = topEssayTitles(entries, ['system', 'framework', 'feedback', 'design', 'model']);
  const agencyEvidence = topEssayTitles(entries, ['agency', 'freedom', 'intrinsic', 'autonomy', 'choice']);
  const uncertaintyEvidence = topEssayTitles(entries, ['uncertainty', 'unknown', 'adapt', 'just start', 'serendipity']);
  const writingEvidence = topEssayTitles(entries, ['writing', 'thinking', 'essay', 'articulate', 'reflect']);
  const executionEvidence = topEssayTitles(entries, ['startup', 'build', 'ship', 'founder', 'market', 'leverage']);

  return (
    <>
      <MobileNavigation />

      <div className="page-shell" style={{ scrollbarGutter: 'stable' }}>
        <div className="flex justify-center">
          <main className="page-main">
            <div className="page-stack">
              <header className="page-header">
                <h1 className="page-title">Profile</h1>
                <p className="page-subtitle">Strict essay-based analysis only ({essays.length} essays)</p>
              </header>

              <section className="space-y-6">
                <div className="border border-[hsl(var(--border)/0.6)] bg-[hsl(var(--card))] p-6">
                  <p className="text-sm text-[hsl(var(--muted-foreground))] leading-relaxed">
                    Note: this profile was generated by AI by analyzing your published essays only.
                  </p>
                </div>

                <div className="border border-[hsl(var(--border)/0.6)] bg-[hsl(var(--card))] p-6 space-y-3">
                  <h2 className="text-xl">MBTI Output (From Text Patterns)</h2>
                  <p className="page-body text-base">
                    <strong>{mbtiGuess}</strong> with strongest signal on <strong>N</strong> and <strong>T</strong>. The J/P axis is unstable in writing:
                    plans are discussed, but action under uncertainty is favored.
                  </p>
                  <p className="text-sm text-[hsl(var(--muted-foreground))]">
                    Evidence essays: {systemsEvidence.join(' • ')}
                  </p>
                </div>

                <div className="border border-[hsl(var(--border)/0.6)] bg-[hsl(var(--card))] p-6 space-y-4">
                  <h2 className="text-xl">Personality Pattern (No Fluff)</h2>
                  <ul className="space-y-3 text-sm leading-relaxed">
                    <li><strong>Cognitive style:</strong> abstract, system-first, contrarian. Frequently rejects default frames.</li>
                    <li><strong>Motivation style:</strong> meaning and autonomy over compliance or status games.</li>
                    <li><strong>Behavioral risk:</strong> can switch from deep recursion to abrupt closure when mental load spikes.</li>
                    <li><strong>Execution risk:</strong> ideation speed often exceeds organizational discipline.</li>
                  </ul>
                  <p className="text-sm text-[hsl(var(--muted-foreground))]">
                    Evidence essays: {agencyEvidence.join(' • ')}
                  </p>
                </div>

                <div className="border border-[hsl(var(--border)/0.6)] bg-[hsl(var(--card))] p-6 space-y-4">
                  <h2 className="text-xl">Learning Style</h2>
                  <ul className="space-y-3 text-sm leading-relaxed">
                    <li><strong>Primary mode:</strong> learn by building and testing, not by passive intake.</li>
                    <li><strong>Acceleration channel:</strong> writing and dialogue are used to debug thinking in real time.</li>
                    <li><strong>Retention filter:</strong> if knowledge is not tied to agency or output, it gets dropped.</li>
                    <li><strong>Failure mode:</strong> too much exploration, not enough repeatable execution loops.</li>
                  </ul>
                  <p className="text-sm text-[hsl(var(--muted-foreground))]">
                    Evidence essays: {writingEvidence.join(' • ')}
                  </p>
                </div>

                <div className="border border-[hsl(var(--border)/0.6)] bg-[hsl(var(--card))] p-6 space-y-4">
                  <h2 className="text-xl">How To Work With This Person</h2>
                  <ul className="space-y-2 text-sm leading-relaxed">
                    <li className="border-l border-[hsl(var(--border))] pl-3">Bring hard problems, constraints, and explicit tradeoffs.</li>
                    <li className="border-l border-[hsl(var(--border))] pl-3">Do not lead with social proof. Lead with mechanism.</li>
                    <li className="border-l border-[hsl(var(--border))] pl-3">Force one written decision memo before major commitments.</li>
                    <li className="border-l border-[hsl(var(--border))] pl-3">Split work into: idea phase, then structure phase, then ship phase.</li>
                  </ul>
                  <p className="text-sm text-[hsl(var(--muted-foreground))]">
                    Evidence essays: {executionEvidence.join(' • ')}
                  </p>
                </div>

                <div className="border border-[hsl(var(--border)/0.6)] bg-[hsl(var(--card))] p-6 space-y-4">
                  <h2 className="text-xl">Current Tension In The Writing</h2>
                  <p className="text-sm leading-relaxed">
                    Recurring conflict: desire for disciplined optimization versus stated preference for uncertainty, emergence, and serendipity.
                    This conflict drives output, but also creates inconsistency.
                  </p>
                  <p className="text-sm text-[hsl(var(--muted-foreground))]">
                    Evidence essays: {uncertaintyEvidence.join(' • ')}
                  </p>
                </div>

                <footer className="page-footer">
                  <p>© <Copyright /> Marius Manolachi</p>
                </footer>
              </section>
            </div>
          </main>

          <DesktopNavigation />
        </div>
      </div>
    </>
  );
}
